version: '3.8'

services:
  reverse-proxy:
    image: traefik:v3.0
    command: --configFile=/traefik.yml # Sử dụng tệp cấu hình
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Giao diện quản trị Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Cho phép Traefik lắng nghe các sự kiện Docker
      - ./traefik.yml:/traefik.yml  # Cấu hình Traefik
    networks:
      - avian_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.services.reverse-proxy.loadbalancer.server.port=8080"

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mongo.rule=HostSNI(`mongo.localhost`)"
      - "traefik.tcp.routers.mongo.entrypoints=mongo"
      - "traefik.tcp.routers.mongo.tls=true"
      - "traefik.tcp.routers.mongo.tls.passthrough=true"
      - "traefik.tcp.routers.mongo.service=kf_stack_mongo"
      - "traefik.tcp.services.kf_stack_mongo.loadbalancer.server.port=27017"
    volumes:
      - ./data/mongodb01:/data/db
    networks:
      - avian_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - avian_network
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`redis.localhost`)"
      - "traefik.tcp.routers.redis.tls=true"
      - "traefik.tcp.routers.redis.tls.passthrough=true"
      - "traefik.tcp.routers.redis.service=kf_stack_redis"
      - "traefik.tcp.services.kf_stack_redis.loadbalancer.server.port=6379"

  avian_service_concerts:
    build:
      context: ../avian_concert
      dockerfile: Dockerfile
    image: avian_concert:latest
    #ports:
    # - "3000:3000"  # Uncomment nếu cần expose port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.concert_root.rule=Host(`api.localhost`) && (PathPrefix(`/v1/seat-types`) || PathPrefix(`/v1/concerts`))"
      - "traefik.http.routers.concert_root.entrypoints=web,websecure"
      - "traefik.http.routers.concert_root.service=avian_service_concerts"
      - "traefik.http.services.avian_service_concerts.loadbalancer.server.port=3000"
    restart: unless-stopped
    entrypoint: /home/node/app/start.sh
    networks:
      - avian_network

volumes:
  redis-data:
    name: redis-data

networks:
  avian_network:
    external: true
