version: '3.8'

services:
  avian_service_concerts:
    build:
      context: .
      dockerfile: Dockerfile
    image: avian_concert:latest
    #ports:
    # - "3000:3000"  # Uncomment nếu cần expose port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.concert_root.rule=Host(`api.minhnguyen.info.vn`) && (PathPrefix(`/v1/seat-types`) || PathPrefix(`/v1/concerts`))"
      - "traefik.http.routers.concert_root.entrypoints=web,websecure"
      - "traefik.http.routers.concert_root.service=avian_service_concerts"
      - "traefik.http.services.avian_service_concerts.loadbalancer.server.port=3000"
    restart: unless-stopped
    entrypoint: /home/node/app/start.sh
    networks:
      - avian_network

networks:
  avian_network:
    external: true