version: '3.8'

services:
  avian_service_auth:
    image: avian_booking:latest
    #ports:
    # - "3000:3000"  # Uncomment nếu cần expose port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booking_root.rule=Host(`api.minhnguyen.info.vn`) && (PathPrefix(`/v1/booking`) || PathPrefix(`/v1/points`))"
      - "traefik.http.routers.booking_root.entrypoints=web,websecure"
      - "traefik.http.routers.booking_root.service=avian_service_booking"
      - "traefik.http.services.avian_service_booking.loadbalancer.server.port=3000"
    restart: unless-stopped
    entrypoint: /home/node/app/start.sh
    networks:
      - kfm_network

networks:
  kfm_network:
    external: true