version: '3.8'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - kfm_network
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`redis.minhnguyen.info.vn`)"
      - "traefik.tcp.routers.redis.tls=true"
      - "traefik.tcp.routers.redis.tls.passthrough=true"
      - "traefik.tcp.routers.redis.service=kf_stack_redis"
      - "traefik.tcp.services.kf_stack_redis.loadbalancer.server.port=6379"

volumes:
  redis-data:
    name: redis-data

networks:
  kfm_network:
    external: true