version: '3.8'

services:
  avian_service_auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: 
      name: avian_auth:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth_root.rule=Host(`api.minhnguyen.info.vn`) && (PathPrefix(`/v1/users`) || PathPrefix(`/v1/points`))"
      - "traefik.http.routers.auth_root.entrypoints=web,websecure"
      - "traefik.http.routers.auth_root.service=avian_service_auth"
      - "traefik.http.services.avian_service_auth.loadbalancer.server.port=3000"
    restart: unless-stopped
    entrypoint: /home/node/app/start.sh
    networks:
      - kfm_network

networks:
  kfm_network:
    external: true